<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/apps/otm/transmission/v6.4"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/ebs_custport_insert"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/http/b2bc_generic_pos_app/gtm_ebs_td_customer_portal_in/gtm_ebs_td_customer_portal_in_client"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/apps/gtm/transmission/v6.4"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/b2bc_generic_pos_app/gtm_ebs_td_customer_portal_in/ebs_custport_insert"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/gtm_ebs_td_customer_portal_in_client.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Transmission"
                                       namespace="http://xmlns.oracle.com/apps/otm/transmission/v6.4"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ebs_custport_insert.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CieGtmCustPortalTempCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ebs_custport_insert"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON MAR 01 13:27:36 EST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="count" select="4"/>
  <xsl:variable name="curElement" select="."/>
  <tns:CieGtmCustPortalTempCollection>
    <xsl:for-each select="1 to $count">
      <tns:CieGtmCustPortalTemp>
        <tns:customerPo>
          <xsl:value-of select="/ns0:Transmission/ns0:TransmissionBody/ns0:GLogXMLElement/ns2:GtmTransaction/ns2:Refnum[ns0:RefnumQualifierGid/ns0:Gid/ns0:Xid='CUSTOMER_PO_NUMBER']/ns0:RefnumValue"/>
          <xsl:variable name="curVal" select="."/>
          <xsl:value-of select="$curElement/Value[. = $curVal]"/>
          <xsl:if test="$curVal != $count">
            <xsl:text>,</xsl:text>
          </xsl:if>
        </tns:customerPo>
      </tns:CieGtmCustPortalTemp>
    </xsl:for-each>
  </tns:CieGtmCustPortalTempCollection>
  <xsl:text>
</xsl:text>
</xsl:stylesheet>
