<wsdl:definitions
     name="ebs_custport_insert"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/b2bc_generic_pos_app/gtm_ebs_td_customer_portal_in/ebs_custport_insert"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/b2bc_generic_pos_app/gtm_ebs_td_customer_portal_in/ebs_custport_insert"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ebs_custport_insert"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ebs_custport_insert_plt" >
    <plt:role name="ebs_custport_insert_role" >
      <plt:portType name="tns:ebs_custport_insert_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ebs_custport_insert" schemaLocation="../Schemas/ebs_custport_insert_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CieGtmCustPortalTempCollection_msg">
        <wsdl:part name="CieGtmCustPortalTempCollection" element="top:CieGtmCustPortalTempCollection"/>
    </wsdl:message>
    <wsdl:portType name="ebs_custport_insert_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:CieGtmCustPortalTempCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
